import fs from 'node:fs/promises'
import assert from 'node:assert/strict'
import { chromium, expect } from '@playwright/test'

assert.equal(process.env.CI, '1')
assert.ok(process.env.SITEPILOT_CI_PASSWORD)
assert.ok(process.env.PREVIEW_SECRET)
const baseURL = 'http://127.0.0.1:3000'
const browser = await chromium.launch()
const checks: string[] = []
try {
  const anonymous = await browser.newContext({ baseURL })
  const publicDraft = await anonymous.request.get('/api/pages?where[slug][equals]=sitepilot-ci&draft=true')
  assert.equal(publicDraft.status(), 200)
  assert.equal((await publicDraft.json()).totalDocs, 0)
  checks.push('anonymous REST request cannot read draft')
  const denied = await anonymous.request.get(`/next/preview?path=/sitepilot-ci&previewSecret=${encodeURIComponent(process.env.PREVIEW_SECRET!)}`, { maxRedirects: 0 })
  assert.equal(denied.status(), 403)
  checks.push('preview secret without reviewer login is denied')
  const page = await anonymous.newPage()
  const publicPage = await page.goto(`${baseURL}/sitepilot-ci`)
  assert.equal(publicPage?.status(), 404)
  checks.push('anonymous website route returns 404 for draft')
  await anonymous.close()

  for (const [name, viewport] of [
    ['desktop', { width: 1440, height: 900 }],
    ['mobile', { width: 375, height: 812 }],
  ] as const) {
    const context = await browser.newContext({ baseURL, viewport })
    const login = await context.request.post('/api/users/login', { data: {
      email: 'sitepilot-ci@example.invalid', password: process.env.SITEPILOT_CI_PASSWORD,
    } })
    assert.equal(login.status(), 200)
    const page = await context.newPage()
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    const preview = await context.request.get(`/next/preview?path=/sitepilot-ci&previewSecret=${encodeURIComponent(process.env.PREVIEW_SECRET!)}`, { maxRedirects: 0 })
    assert.equal(preview.status(), 307)
    const response = await page.goto(`${baseURL}/sitepilot-ci`)
    assert.equal(response?.status(), 200)
    await expect(page.getByRole('heading', { name: 'SitePilot CMS draft preview', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Review this synthetic website draft', exact: true })).toBeVisible()
    await expect(page.locator('article')).toContainText('Synthetic content generated by the SitePilot draft planner')
    await expect(page).toHaveTitle('SitePilot synthetic acceptance website | Payload Website Template')
    await page.waitForTimeout(1000)
    assert.deepEqual(errors, [], `${name} client errors`)
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1)
    assert.equal(overflow, false, `${name} horizontal overflow`)
    await page.screenshot({ path: `sitepilot-${name}.png`, fullPage: true })
    checks.push(`${name}: authenticated draft renders CMS hero, content, CTA and SEO without client errors or overflow`)
    await context.close()
  }
  await fs.writeFile('./sitepilot-preview-report.json', JSON.stringify({
    synthetic: true, preview: 'ephemeral GitHub runner only', checks,
    limitations: ['compile mode only; full type check and production route generation pending', 'no customer input, CodeAtlas retrieval, form or multilingual acceptance in this fixture'],
  }, null, 2))
  console.log(checks.join('\n'))
} finally {
  await browser.close()
}
