import fs from 'node:fs/promises';
import { createPayloadDraftPlan } from '../src/payload-template.js';
import lock from '../sources/payload-website.lock.json' with { type: 'json' };

// Synthetic acceptance data, never customer claims or an approved delivery.
const plan = createPayloadDraftPlan({
  projectId: 'ci-synthetic-website',
  strategy: { pageHierarchy: ['sitepilot-ci'], blocks: ['Hero', 'Content', 'CTA'] },
  locales: ['en'],
  contentByPage: {
    'sitepilot-ci': {
      title: 'SitePilot synthetic acceptance website',
      heroTitle: 'SitePilot CMS draft preview',
      description: 'Synthetic content generated by the SitePilot draft planner for CI acceptance only.',
      cta: 'Review this synthetic website draft',
      claimRefs: ['ci-synthetic-content-v1'],
    },
  },
});
await fs.mkdir('ci-results', { recursive: true });
await fs.writeFile('ci-results/draft-plan.json', JSON.stringify({ ...plan, synthetic: true, sourceCommit: lock.commit }, null, 2));
console.log('Generated one synthetic draft using the SitePilot Payload planner.');
